apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-final-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-final-app
  template:
    metadata:
      labels:
        app: jenkins-final-app
    spec:
      containers:
        - name: jenkins-final-app
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
          env:
            - name: APP_ENV
              value: ENV_PLACEHOLDER
